name: Build Container and Upload as Release

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 安裝 Podman & gzip
        run: |
          sudo apt update

      - name: 建構 container image
        run: |
          podman build -f Containerfile.builder -t sinopac.io/cpp-builder:latest .
          
      - name: 儲存 image
        run: |
          mkdir -p docker-images
          podman save sinopac.io/cpp-builder:latest > cpp-builder.tar

      - name: 建立 Release 並上傳映像
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cpp-builder-v1
          name: "C++ Builder Image v1"
          files: |
            docker-images/cpp-builder.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
